apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  labels: { app: vllm }
spec:
  type: NodePort
  selector: { app: vllm }
  sessionAffinity: None
  ports:
    - name: http-vllm
      port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 31286

